pre-release-commit-message = "chore({{crate_name}}): Release {{version}}"
no-dev-version = true
tag-message = "{{tag_name}}"
tag-name = "{{prefix}}v{{version}}"
pre-release-replacements = [
  {file="README.md", search="assert_fs = .*", replace="assert_fs = \"{{version}}\""},
  {file="src/lib.rs", search="assert_fs = .*", replace="assert_fs = \"{{version}}\""},
]
